apiVersion: v1
kind: Pod
metadata:
  name: load-stresser-node01
  labels:
spec:
  nodeName: station01-b205
  containers:
    - name: web
      image: ttsourdinis/node-stresser
      command: ["/bin/bash", "-c"]
      securityContext:
        privileged: true
      args:
      -  while true;
         do sleep 30;
         done;

