apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtt-monitor-node01
  labels:
    app: rtt-monitor-node01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtt-monitor-node01
      run: rtt-monitor-node01
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtt-node01-net
      labels:
        app: rtt-monitor-node01
        run: rtt-monitor-node01
    spec:
      nodeName: station01-b205
      containers:
      - name: rtt-monitor-node01
        imagePullPolicy: Always
        securityContext:
          privileged: true
        image: ttsourdinis/export_rtt:node01
        ports:
        - name: web
          containerPort: 9888
          protocol: TCP

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rtt-node01-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "routes": [ { "dst": "12.1.1.129/32", "gw": "192.168.70.143" } ], "addresses": [ { "address": "192.168.70.147/24",
    "gateway": "192.168.70.1" } ] } }'


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtt-monitor-node01
  name: rtt-monitor-node01
spec:
  type: NodePort
  ports:
  - name: web
    port: 9888
    targetPort: web
    protocol: TCP
    nodePort: 30007
  selector:
    app: rtt-monitor-node01

---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: rtt-monitor-node01
  labels:
    app: rtt-monitor-node01
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rtt-monitor-node01
  endpoints:
  - port: web
    interval: 5s
  namespaceSelector:
    matchNames:
      - default



