version: '3.8'
services:
    oai-gnb:
        image: oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment: 
            RFSIMULATOR: server
            USE_SA_TDD_MONO: 'yes'
            GNB_NAME: gnb-rfsim
            TAC: 0x0001
            MCC: '208'
            MNC: '95'
            MNC_LENGTH: 2
            NSSAI_SST: 1
            NSSAI_SD0: 27db
            NSSAI_SD1: 1
            AMF_IP_ADDRESS: 192.168.22.196
            GNB_NGA_IF_NAME: eth0
            GNB_NGA_IP_ADDRESS: 192.168.22.240
            GNB_NGU_IF_NAME: eth0
            GNB_NGU_IP_ADDRESS: 192.168.22.240
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.22.240
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue
        environment: 
            RFSIMULATOR: 192.168.22.240
            FULL_IMSI: '208950000000031'
            FULL_KEY: '0C0A34601D4F07677303652C0462535B'
            OPC: '63bfa50ee6523365ff14c1f45f88737d'
            DNN: oai
            NSSAI_SST: 1
            NSSAI_SD: 1
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        networks:
            public_net:
                ipv4_address: 192.168.22.250
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue2:
        image: oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue2
        environment: 
            RFSIMULATOR: 192.168.22.240
            FULL_IMSI: '208950000000032'
            FULL_KEY: '0C0A34601D4F07677303652C0462535B'
            OPC: '63bfa50ee6523365ff14c1f45f88737d'
            DNN: oai
            NSSAI_SST: 1
            NSSAI_SD: 1
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        networks:
            public_net:
                ipv4_address: 192.168.22.251
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        external:
            name: demo-oai-public-net

