---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: mysql-net
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
          # Use secret in real usage
        - name: TZ
          value: Europe/Paris

        - name: MYSQL_DATABASE
          value: oai_db

        - name: MYSQL_USER
          value: test

        - name: MYSQL_PASSWORD
          value: test     

        - name: MYSQL_ROOT_PASSWORD
          value: linux

        - name: MYSQL_ROOT_HOST
          value: "0.0.0.0"

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";
    CREATE TABLE `AccessAndMobilitySubscriptionData` (
    `ueid` varchar(15) NOT NULL,
    `servingPlmnid` varchar(15) NOT NULL,
    `supportedFeatures` varchar(50) DEFAULT NULL,
    `gpsis` json DEFAULT NULL,
    `internalGroupIds` json DEFAULT NULL,
    `sharedVnGroupDataIds` json DEFAULT NULL,
    `subscribedUeAmbr` json DEFAULT NULL,
    `nssai` json DEFAULT NULL,
    `ratRestrictions` json DEFAULT NULL,
    `forbiddenAreas` json DEFAULT NULL,
    `serviceAreaRestriction` json DEFAULT NULL,
    `coreNetworkTypeRestrictions` json DEFAULT NULL,
    `rfspIndex` int(10) DEFAULT NULL,
    `subsRegTimer` int(10) DEFAULT NULL,
    `ueUsageType` int(10) DEFAULT NULL,
    `mpsPriority` tinyint(1) DEFAULT NULL,
    `mcsPriority` tinyint(1) DEFAULT NULL,
    `activeTime` int(10) DEFAULT NULL,
    `sorInfo` json DEFAULT NULL,
    `sorInfoExpectInd` tinyint(1) DEFAULT NULL,
    `sorafRetrieval` tinyint(1) DEFAULT NULL,
    `sorUpdateIndicatorList` json DEFAULT NULL,
    `upuInfo` json DEFAULT NULL,
    `micoAllowed` tinyint(1) DEFAULT NULL,
    `sharedAmDataIds` json DEFAULT NULL,
    `odbPacketServices` json DEFAULT NULL,
    `serviceGapTime` int(10) DEFAULT NULL,
    `mdtUserConsent` json DEFAULT NULL,
    `mdtConfiguration` json DEFAULT NULL,
    `traceData` json DEFAULT NULL,
    `cagData` json DEFAULT NULL,
    `stnSr` varchar(50) DEFAULT NULL,
    `cMsisdn` varchar(50) DEFAULT NULL,
    `nbIoTUePriority` int(10) DEFAULT NULL,
    `nssaiInclusionAllowed` tinyint(1) DEFAULT NULL,
    `rgWirelineCharacteristics` varchar(50) DEFAULT NULL,
    `ecRestrictionDataWb` json DEFAULT NULL,
    `ecRestrictionDataNb` tinyint(1) DEFAULT NULL,
    `expectedUeBehaviourList` json DEFAULT NULL,
    `primaryRatRestrictions` json DEFAULT NULL,
    `secondaryRatRestrictions` json DEFAULT NULL,
    `edrxParametersList` json DEFAULT NULL,
    `ptwParametersList` json DEFAULT NULL,
    `iabOperationAllowed` tinyint(1) DEFAULT NULL,
    `wirelineForbiddenAreas` json DEFAULT NULL,
    `wirelineServiceAreaRestriction` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `Amf3GppAccessRegistration` (
    `ueid` varchar(15) NOT NULL,
    `amfInstanceId` varchar(50) NOT NULL,
    `supportedFeatures` varchar(50) DEFAULT NULL,
    `purgeFlag` tinyint(1) DEFAULT NULL,
    `pei` varchar(50) DEFAULT NULL,
    `imsVoPs` json DEFAULT NULL,
    `deregCallbackUri` varchar(50) NOT NULL,
    `amfServiceNameDereg` json DEFAULT NULL,
    `pcscfRestorationCallbackUri` varchar(50) DEFAULT NULL,
    `amfServiceNamePcscfRest` json DEFAULT NULL,
    `initialRegistrationInd` tinyint(1) DEFAULT NULL,
    `guami` json NOT NULL,
    `backupAmfInfo` json DEFAULT NULL,
    `drFlag` tinyint(1) DEFAULT NULL,
    `ratType` json NOT NULL,
    `urrpIndicator` tinyint(1) DEFAULT NULL,
    `amfEeSubscriptionId` varchar(50) DEFAULT NULL,
    `epsInterworkingInfo` json DEFAULT NULL,
    `ueSrvccCapability` tinyint(1) DEFAULT NULL,
    `registrationTime` varchar(50) DEFAULT NULL,
    `vgmlcAddress` json DEFAULT NULL,
    `contextInfo` json DEFAULT NULL,
    `noEeSubscriptionInd` tinyint(1) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `AuthenticationStatus` (
    `ueid` varchar(20) NOT NULL,
    `nfInstanceId` varchar(50) NOT NULL,
    `success` tinyint(1) NOT NULL,
    `timeStamp` varchar(50) NOT NULL,
    `authType` varchar(25) NOT NULL,
    `servingNetworkName` varchar(50) NOT NULL,
    `authRemovalInd` tinyint(1) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `AuthenticationSubscription` (
    `ueid` varchar(20) NOT NULL,
    `authenticationMethod` varchar(25) NOT NULL,
    `encPermanentKey` varchar(50) DEFAULT NULL,
    `protectionParameterId` varchar(50) DEFAULT NULL,
    `sequenceNumber` json DEFAULT NULL,
    `authenticationManagementField` varchar(50) DEFAULT NULL,
    `algorithmId` varchar(50) DEFAULT NULL,
    `encOpcKey` varchar(50) DEFAULT NULL,
    `encTopcKey` varchar(50) DEFAULT NULL,
    `vectorGenerationInHss` tinyint(1) DEFAULT NULL,
    `n5gcAuthMethod` varchar(15) DEFAULT NULL,
    `rgAuthenticationInd` tinyint(1) DEFAULT NULL,
    `supi` varchar(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    INSERT INTO `AuthenticationSubscription` (`ueid`, `authenticationMethod`, `encPermanentKey`, `protectionParameterId`, `sequenceNumber`, `authenticationManagementField`, `algorithmId`, `encOpcKey`, `encTopcKey`, `vectorGenerationInHss`, `n5gcAuthMethod`, `rgAuthenticationInd`, `supi`) VALUES
    ('208950000000031', '5G_AKA', '0C0A34601D4F07677303652C0462535B', '0C0A34601D4F07677303652C0462535B', '{\"sqn\": \"000000000020\", \"sqnScheme\": \"NON_TIME_BASED\", \"lastIndexes\": {\"ausf\": 0}}', '8000', 'milenage', '63bfa50ee6523365ff14c1f45f88737d', NULL, NULL, NULL, NULL, '208950000000031'),
    ('208950000000032', '5G_AKA', '0C0A34601D4F07677303652C0462535B', '0C0A34601D4F07677303652C0462535B', '{\"sqn\": \"000000000020\", \"sqnScheme\": \"NON_TIME_BASED\", \"lastIndexes\": {\"ausf\": 0}}', '8000', 'milenage', '63bfa50ee6523365ff14c1f45f88737d', NULL, NULL, NULL, NULL, '208950000000032'),
    ('208950000000033', '5G_AKA', '0C0A34601D4F07677303652C0462535B', '0C0A34601D4F07677303652C0462535B', '{\"sqn\": \"000000000020\", \"sqnScheme\": \"NON_TIME_BASED\", \"lastIndexes\": {\"ausf\": 0}}', '8000', 'milenage', '63bfa50ee6523365ff14c1f45f88737d', NULL, NULL, NULL, NULL, '208950000000033');
    CREATE TABLE `SdmSubscriptions` (
    `ueid` varchar(15) NOT NULL,  
    `subsId` int(10) UNSIGNED NOT NULL,
    `nfInstanceId` varchar(50) NOT NULL,
    `implicitUnsubscribe` tinyint(1) DEFAULT NULL,
    `expires` varchar(50) DEFAULT NULL,
    `callbackReference` varchar(50) NOT NULL,
    `amfServiceName` json DEFAULT NULL,
    `monitoredResourceUris` json NOT NULL,
    `singleNssai` json DEFAULT NULL,
    `dnn` varchar(50) DEFAULT NULL,
    `subscriptionId` varchar(50) DEFAULT NULL,
    `plmnId` json DEFAULT NULL,
    `immediateReport` tinyint(1) DEFAULT NULL,
    `report` json DEFAULT NULL,
    `supportedFeatures` varchar(50) DEFAULT NULL,
    `contextInfo` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `SessionManagementSubscriptionData` (
    `ueid` varchar(15) NOT NULL,
    `servingPlmnid` varchar(15) NOT NULL,
    `singleNssai` json NOT NULL,
    `dnnConfigurations` json DEFAULT NULL,
    `internalGroupIds` json DEFAULT NULL,
    `sharedVnGroupDataIds` json DEFAULT NULL,
    `sharedDnnConfigurationsId` varchar(50) DEFAULT NULL,
    `odbPacketServices` json DEFAULT NULL,
    `traceData` json DEFAULT NULL,
    `sharedTraceDataId` varchar(50) DEFAULT NULL,
    `expectedUeBehavioursList` json DEFAULT NULL,
    `suggestedPacketNumDlList` json DEFAULT NULL,
    `3gppChargingCharacteristics` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    INSERT INTO `SessionManagementSubscriptionData` (`ueid`, `servingPlmnid`, `singleNssai`, `dnnConfigurations`) VALUES 
    ('208950000000031', '20895', '{\"sst\": 1, \"sd\": \"1\"}','{\"default\":{\"pduSessionTypes\":{ \"defaultSessionType\": \"IPV4\"},\"sscModes\": {\"defaultSscMode\": \"SSC_MODE_1\"},\"5gQosProfile\": {\"5qi\": 6,\"arp\":{\"priorityLevel\": 1,\"preemptCap\": \"NOT_PREEMPT\",\"preemptVuln\":\"NOT_PREEMPTABLE\"},\"priorityLevel\":1},\"sessionAmbr\":{\"uplink\":\"100Mbps\", \"downlink\":\"100Mbps\"},\"staticIpAddress\":[{\"ipv4Addr\": \"12.1.1.4\"}]}}');
    INSERT INTO `SessionManagementSubscriptionData` (`ueid`, `servingPlmnid`, `singleNssai`, `dnnConfigurations`) VALUES 
    ('208950000000032', '20895', '{\"sst\": 222, \"sd\": \"123\"}','{\"default\":{\"pduSessionTypes\":{ \"defaultSessionType\": \"IPV4\"},\"sscModes\": {\"defaultSscMode\": \"SSC_MODE_1\"},\"5gQosProfile\": {\"5qi\": 6,\"arp\":{\"priorityLevel\": 1,\"preemptCap\": \"NOT_PREEMPT\",\"preemptVuln\":\"NOT_PREEMPTABLE\"},\"priorityLevel\":1},\"sessionAmbr\":{\"uplink\":\"100Mbps\", \"downlink\":\"100Mbps\"}}}');
    CREATE TABLE `SmfRegistrations` (
    `ueid` varchar(15) NOT NULL,
    `subpduSessionId` int(10) NOT NULL,
    `smfInstanceId` varchar(50) NOT NULL,
    `smfSetId` varchar(50) DEFAULT NULL,
    `supportedFeatures` varchar(50) DEFAULT NULL,
    `pduSessionId` int(10) NOT NULL,
    `singleNssai` json NOT NULL,
    `dnn` varchar(50) DEFAULT NULL,
    `emergencyServices` tinyint(1) DEFAULT NULL,
    `pcscfRestorationCallbackUri` varchar(50) DEFAULT NULL,
    `plmnId` json NOT NULL,
    `pgwFqdn` varchar(50) DEFAULT NULL,
    `epdgInd` tinyint(1) DEFAULT NULL,
    `deregCallbackUri` varchar(50) DEFAULT NULL,
    `registrationReason` json DEFAULT NULL,
    `registrationTime` varchar(50) DEFAULT NULL,
    `contextInfo` json DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `SmfSelectionSubscriptionData` (
    `ueid` varchar(15) NOT NULL,
    `servingPlmnid` varchar(15) NOT NULL,
    `supportedFeatures` varchar(50) DEFAULT NULL,
    `subscribedSnssaiInfos` json DEFAULT NULL,
    `sharedSnssaiInfosId` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ALTER TABLE `AccessAndMobilitySubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;
    ALTER TABLE `Amf3GppAccessRegistration`
      ADD PRIMARY KEY (`ueid`);    
    ALTER TABLE `AuthenticationStatus`
      ADD PRIMARY KEY (`ueid`);
    ALTER TABLE `AuthenticationSubscription`
      ADD PRIMARY KEY (`ueid`);
    ALTER TABLE `SdmSubscriptions`
      ADD PRIMARY KEY (`subsId`,`ueid`) USING BTREE;
    ALTER TABLE `SessionManagementSubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;
    ALTER TABLE `SmfRegistrations`
      ADD PRIMARY KEY (`ueid`,`subpduSessionId`) USING BTREE;
    ALTER TABLE `SmfSelectionSubscriptionData`
      ADD PRIMARY KEY (`ueid`,`servingPlmnid`) USING BTREE;
    ALTER TABLE `SdmSubscriptions`
      MODIFY `subsId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
    COMMIT;                








---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: mysql-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.131/24",
    "gateway": "192.168.70.1" } ] } }'
    

