# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: oai-nrf
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: oai-nrf
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nrf
spec:
  selector:
    matchLabels:
      app: oai-nrf
  strategy:
    type: Recreate
  template:
    metadata:
      name: oai-nrf
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-nrf-net
      labels:
        app: oai-nrf
    spec:
      hostAliases:
      - ip: "192.168.70.134"
        hostnames:
        - "oai-spgwu"

      - ip: "192.168.70.130"
        hostnames:
        - "oai-nrf"

      - ip: "192.168.70.136"
        hostnames:
        - "oai-udr"

      - ip: "192.168.70.137"
        hostnames:
        - "oai-udm"

      - ip: "192.168.70.138"
        hostnames:
        - "oai-ausf"        

      - ip: "192.168.70.133"
        hostnames:
        - "oai-smf"

      - ip: "192.168.70.132"
        hostnames:
        - "oai-amf"       
      containers:           
      - image: oaisoftwarealliance/oai-nrf:v1.4.0
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: true
        name: oai-nrf
        env:
          # Use secret in real usage
        - name: NRF_INTERFACE_NAME_FOR_SBI
          value: "net1"

        - name: NRF_INTERFACE_PORT_FOR_SBI
          value: "80"

        - name: NRF_INTERFACE_HTTP2_PORT_FOR_SBI
          value: "8080"

        - name: NRF_API_VERSION
          value: "v1"

        - name: INSTANCE
          value: "0"

        - name: PID_DIRECTORY
          value: /var/run
   
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-nrf-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.130/24",
    "gateway": "192.168.70.1" } ] } }'
    

