# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: oai-udr
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: oai-udr
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-udr
spec:
  selector:
    matchLabels:
      app: oai-udr
  strategy:
    type: Recreate
  template:
    metadata:
      name: oai-udr
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-udr-net
      labels:
        app: oai-udr
    spec:
      hostAliases:
      - ip: "192.168.70.134"
        hostnames:
        - "oai-spgwu"

      - ip: "192.168.70.130"
        hostnames:
        - "oai-nrf"

      - ip: "192.168.70.136"
        hostnames:
        - "oai-udr"

      - ip: "192.168.70.137"
        hostnames:
        - "oai-udm"

      - ip: "192.168.70.138"
        hostnames:
        - "oai-ausf"        

      - ip: "192.168.70.133"
        hostnames:
        - "oai-smf"

      - ip: "192.168.70.132"
        hostnames:
        - "oai-amf"    
      containers:
      - image: oaisoftwarealliance/oai-udr:v1.4.0
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: true
        name: oai-udr
        env:
          # Use secret in real usage
        - name: TZ
          value: Europe/Paris

        - name: INSTANCE
          value: "0"

        - name: PID_DIRECTORY
          value: /var/run

        - name: UDR_INTERFACE_NAME_FOR_NUDR
          value: net1    

        - name: UDR_INTERFACE_PORT_FOR_NUDR
          value: "80"

        - name: UDR_INTERFACE_HTTP2_PORT_FOR_NUDR
          value: "8080"

        - name: UDR_API_VERSION
          value: "v1"  

        - name: MYSQL_IPV4_ADDRESS
          value: "192.168.70.131"

        - name: MYSQL_USER
          value: test

        - name: MYSQL_PASS
          value: test

        - name: MYSQL_DB
          value: oai_db
        
        - name: WAIT_MYSQL
          value: "120"

        - name: USE_FQDN_DNS
          value: "yes"

        - name: NRF_FQDN
          value: oai-nrf
        
        - name: REGISTER_NRF
          value: "yes"

        - name: NRF_IPV4_ADDRESS
          value: "192.168.70.130"

        - name: NRF_PORT
          value: "80"

        - name: USE_HTTP2
          value: "no"

        - name: NRF_API_VERSION
          value: "v1"              
  

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-udr-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.136/24",
    "gateway": "192.168.70.1" } ] } }'
    

