apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "ubuntu-data-volume2"
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
  pvc:
    storageClassName: nfs-client
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi








