# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: oai-nssf
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: oai-nssf
# ---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nssf-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nssf
spec:
  selector:
    matchLabels:
      app: oai-nssf
  strategy:
    type: Recreate
  template:
    metadata:
      name: oai-nssf
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-nssf-net
      labels:
        app: oai-nssf
    spec:
      hostAliases:

      - ip: "192.168.70.132"
        hostnames:
        - "oai-nssf"

      - ip: "192.168.70.133"
        hostnames:
        - "oai-udr"

      - ip: "192.168.70.134"
        hostnames:
        - "oai-udm"        

      - ip: "192.168.70.135"
        hostnames:
        - "oai-ausf"  

      - ip: "192.168.70.136"
        hostnames:
        - "oai-nrf-slice12"

      - ip: "192.168.70.137"
        hostnames:
        - "oai-nrf-slice3"        
 
      - ip: "192.168.70.138"
        hostnames:
        - "oai-amf"

      - ip: "192.168.70.139"
        hostnames:
        - "oai-smf-slice1"

      - ip: "192.168.70.140"
        hostnames:
        - "oai-smf-slice2"

      - ip: "192.168.70.141"
        hostnames:
        - "oai-smf-slice3" 

      - ip: "192.168.70.142"
        hostnames:
        - "oai-spgwu-slice1"

      - ip: "192.168.70.143"
        hostnames:
        - "oai-spgwu-slice2"

      - ip: "192.168.70.144"
        hostnames:
        - "oai-vpp-upf-slice3" 
      volumes:
          - name: nssf-pvc
            nfs:
              server: master
              path: /mnt/nfs_server_files/
      containers:
      - image: oaisoftwarealliance/oai-nssf:v1.4.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /openair-nssf/etc/nssf_slice_config.yaml
            name: nssf-pvc
            subPath: nssf_slice_config.yaml

        securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
              drop: ["ALL"]
        name: oai-nssf
        env:
          # Use secret in real usage
        - name: TZ
          value: Europe/Paris

        - name: INSTANCE
          value: "0"

        - name: PID_DIRECTORY
          value: /var/run

        - name: NSSF_NAME
          value: oai-nssf    

        - name: NSSF_FQDN
          value: "192.168.70.132"

        - name: SBI_IF_NAME
          value: net1

        - name: SBI_PORT
          value: "80"

        - name: SBI_API_VERSION
          value: v1

        - name: SBI_PORT_HTTP1
          value: "80"

        - name: SBI_PORT_HTTP2
          value: "8080"
        
        - name: NSSF_SLICE_CONFIG
          value: "/openair-nssf/etc/nssf_slice_config.yaml"       

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-nssf-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.132/24",
    "gateway": "192.168.70.1" } ] } }'
    
