kubectl delete -f oai-nr-ue2.yaml 
kubectl delete -f oai-nr-ue1.yaml 
kubectl delete -f oai-gnbsim1.yaml 
kubectl delete -f oai-gnbsim2.yaml 
kubectl delete -f oai-spgwu-slice1.yaml 
kubectl delete -f oai-spgwu-slice2.yaml 
kubectl delete -f oai-vpp-upf-slice3.yaml 
kubectl delete -f oai-smf-slice1.yaml 
kubectl delete -f oai-smf-slice2.yaml 
kubectl delete -f oai-smf-slice3.yaml 
kubectl delete -f oai-amf.yaml 
kubectl delete -f oai-nrf-slice12.yaml 
kubectl delete -f oai-nrf-slice3.yaml 
kubectl delete -f oai-udm.yaml 
kubectl delete -f oai-udr.yaml 
kubectl delete -f oai-ausf.yaml 
kubectl delete -f oai-ext-dn.yaml 
kubectl delete -f oai-nssf.yaml 
kubectl delete -f mysql.yaml 
kubectl delete -f ueransim.yaml
