# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: oai-vpp-upf-slice3
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: oai-vpp-upf-slice3
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-vpp-upf-slice3
spec:
  selector:
    matchLabels:
      app: oai-vpp-upf-slice3
  strategy:
    type: Recreate
  template:
    metadata:
      name: oai-vpp-upf-slice3
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-vpp-upf-slice3-net1, oai-vpp-upf-slice3-net2, oai-vpp-upf-slice3-net3
      labels:
        app: oai-vpp-upf-slice3
    spec:
      hostAliases:
      - ip: "192.168.70.132"
        hostnames:
        - "oai-nssf"

      - ip: "192.168.70.133"
        hostnames:
        - "oai-udr"

      - ip: "192.168.70.134"
        hostnames:
        - "oai-udm"        

      - ip: "192.168.70.135"
        hostnames:
        - "oai-ausf"  

      - ip: "192.168.70.136"
        hostnames:
        - "oai-nrf-slice12"

      - ip: "192.168.70.137"
        hostnames:
        - "oai-nrf-slice3"        
 
      - ip: "192.168.70.138"
        hostnames:
        - "oai-amf"

      - ip: "192.168.70.139"
        hostnames:
        - "oai-smf-slice1"

      - ip: "192.168.70.140"
        hostnames:
        - "oai-smf-slice2"

      - ip: "192.168.70.141"
        hostnames:
        - "oai-smf-slice3" 

      - ip: "192.168.70.142"
        hostnames:
        - "oai-spgwu-slice1"

      - ip: "192.168.70.143"
        hostnames:
        - "oai-spgwu-slice2"

      - ip: "192.168.70.144"
        hostnames:
        - "oai-vpp-upf-slice3"    
      containers:
      - image: oaisoftwarealliance/oai-upf-vpp:v1.4.0
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
              drop: ["ALL"]
        name: oai-spgwu-slice1
        env:
          # Use secret in real usage
        - name: NWI_N3
          value: access.oai.org

        - name: NWI_N6
          value: "core.oai.org"

        - name: GW_ID
          value: "1"            

        - name: MNC03
          value: "95"

        - name: MCC
          value: "208"

        - name: REALM
          value: "3gppnetwork.org"              

        - name: NETWORK_UE_IP
          value: 12.2.1.0/24

        - name: N3_IPV4_ADDRESS_REMOTE
          value: "192.168.72.156"

        - name: N6_IPV4_ADDRESS_REMOTE
          value: "192.168.73.145"

        - name: VPP_MAIN_CORE
          value: "0"

        - name: VPP_CORE_WORKER
          value: "1"                  

        - name: VPP_PLUGIN_PATH
          value: "/usr/lib/x86_64-linux-gnu/vpp_plugins/"  

        - name: INTERFACE_ACCESS
          value: "net2"  

        - name: INTERFACE_CORE
          value: "net3"  

        - name: INTERFACE_CP
          value: "net1"   

        - name: ENABLE_5G_FEATURES
          value: "yes"  

        - name: NSSAI_SD_0
          value: "130"  

        - name: SST
          value: "130"  

        - name: DNN
          value: "oai.ipv4"  

        - name: REGISTER_NRF
          value: "yes"  

        - name: NRF_IP_ADDR
          value: "192.168.70.137"  

        - name: NRF_PORT
          value: "8080"  

        - name: HTTP_VERSION
          value: "v2"  
  

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-vpp-upf-slice3-net1
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.144/24",
    "gateway": "192.168.70.1" } ] } }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-vpp-upf-slice3-net2
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.72.144/24",
    "gateway": "192.168.72.1" } ] } }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-vpp-upf-slice3-net3
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.73.144/24",
    "gateway": "192.168.73.1" } ] } }'
    

