version: '3.8'
services:
    oai_spgwu_slice1:
        container_name: oai-spgwu-slice2
        image: oai-spgwu-tiny:v1.4.0
        network_mode: "host"
        environment:
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=enp2s0
            - SGW_INTERFACE_NAME_FOR_SX=enp2s0
            - PGW_INTERFACE_NAME_FOR_SGI=enp2s0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - BYPASS_UL_PFCP_RULES=no
            - MCC=208
            - MNC=95
            - MNC03=095
            - TAC=40960
            - GW_ID=1
            - REALM=openairinterface.org
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=192.168.70.143
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=192.168.70.136
            - NSSAI_SST_0=1
            - NSSAI_SD_0=0
            - DNN_0=default

        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
