apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/vm: upf2
  name: upf2
spec:
  domain:
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: virtio
        name: datavolumedisk1
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: default
      - bridge: {}
        name: vm-net2
    resources:
      requests:
        memory: 2048M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: vm-net2
    name: vm-net2
  volumes:
  - dataVolume:
      name: ubuntu-data-volume
    name: datavolumedisk2
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: ubuntu
        ssh_pwauth: True
        chpasswd: { expire: False }
      networkData: |
            version: 2
            ethernets:
              enp2s0:
                addresses:
                - 192.168.70.143/24
              enp1s0:
                dhcp4: true
    name: cloudinitdisk

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-net2
spec:
  config: '{ "cniVersion": "0.3.0", "type": "bridge", "bridge": "br0" }'

