#apiVersion: v1
#kind: Service
#metadata:
#  name: chat-service
#spec:
#  clusterIP: 10.104.181.52
#  selector:
#    app: server
#  ports:
#  - port: 5555
#    targetPort: 5555

#---

apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
  annotations:
    k8s.v1.cni.cncf.io/networks: server-net
    #snapshotPolicy: "checkpoint"
    #snapshotPath: "/var/lib/kubelet/migration/abc"
spec:
  containers:
  - name: server
    securityContext:
      privileged: true
    imagePullPolicy: Always
    image: ttsourdinis/test-server
    ports:
    - containerPort: 5555
      protocol: TCP

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: server-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.70.145/24",
    "gateway": "192.168.70.1" } ] } }'

