apiVersion: v1
kind: Pod
metadata:
  name: sipp1
  labels:
    app: sipp1
  annotations:
    k8s.v1.cni.cncf.io/networks: sipp1-net
    #snapshotPolicy: "checkpoint"
    #snapshotPath: "/var/lib/kubelet/migration/abc"
spec:
  containers:
  - name: sipp1
    securityContext:
      privileged: true
    imagePullPolicy: Always
    image: ctaloi/sipp
    ports:
    - containerPort: 1234
      protocol: TCP
    args: ["-sn", "uas", "-i", "192.168.70.145", "-p", "5555"]


---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sipp1-net
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addroutes": [{"dst": "12.1.1.129", "gw": "192.168.70.143"}], "addresses": [ { "address": "192.168.70.145/24",
    "gateway": "192.168.70.1" } ] } }'



