apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  type: NodePort
  selector:
    app: video
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: video
  labels:
    app: video
  #annotations:
    #snapshotPolicy: "checkpoint"
    #snapshotPath: "/var/lib/kubelet/migration/abc"
spec:
  containers:
  - name: vlc
    securityContext:
      privileged: true
    image: tuongvx/vlc-app:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    #args: ["big_buck_bunny.mp4","--loop","--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]
    args: ["frozen.mp4","--loop","--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]


